# Do you want health to be split across different world groups
isHealthSplit: true

# Do you want hunger levels to be split across different world groups
isHungerSplit: true

# Do you want exp split across different world groups
# *Currently doesn't work due to Bukkit exp bugs*
isExpSplit: false

# Do you want to allow this plugin to control which worlds are creative/survival
worldTypes: true

# Players you wish to never switch inventories (using YML lists)
ignore:
- Pluckerpluck
- randomStranger